In [1]:
from torch.distributions import Categorical
import torch

help(Categorical)

Help on class Categorical in module torch.distributions.categorical:

class Categorical(torch.distributions.distribution.Distribution)
 |  Creates a categorical distribution parameterized by either :attr:`probs` or
 |  :attr:`logits` (but not both).
 |  
 |  .. note::
 |      It is equivalent to the distribution that :func:`torch.multinomial`
 |      samples from.
 |  
 |  Samples are integers from :math:`\{0, \ldots, K-1\}` where `K` is ``probs.size(-1)``.
 |  
 |  If `probs` is 1-dimensional with length-`K`, each element is the relative probability
 |  of sampling the class at that index.
 |  
 |  If `probs` is N-dimensional, the first N-1 dimensions are treated as a batch of
 |  relative probability vectors.
 |  
 |  .. note:: The `probs` argument must be non-negative, finite and have a non-zero sum,
 |            and it will be normalized to sum to 1 along the last dimension. attr:`probs`
 |            will return this normalized value.
 |            The `logits` argument will be i

In [9]:
x = torch.rand(5)
x = torch.softmax(x, dim=-1)

m = Categorical(x)

In [12]:
print(m.probs)

tensor([0.2171, 0.1845, 0.1210, 0.2078, 0.2696])


In [13]:
x 

tensor([0.2171, 0.1845, 0.1210, 0.2078, 0.2696])

In [16]:
m.logits

tensor([-1.5273, -1.6900, -2.1119, -1.5711, -1.3110])

In [17]:
torch.log(x)

tensor([-1.5273, -1.6900, -2.1119, -1.5711, -1.3110])

In [19]:
def _KL_categorical(dist1: Categorical, dist2: Categorical):
    """KL(P || Q) where
    dist1: P
    dist2: Q
    P, Q are categocial
    """
    p = dist1.probs
    q = dist2.probs
    kl = torch.sum(p*(torch.log(p) - torch.log(q)))
    return kl

In [20]:
_KL_categorical(m, m)

tensor(0.)

In [23]:
import numpy as np
np.float('-inf') < 0

True